<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ny_slider"
 *
 * Auto generated by Extension Builder 2019-08-15
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Content Slider',
    'description' => 'Add a content slider as a custom content element',
    'category' => 'plugin',
    'author' => 'Nara Yaralyan',
    'author_email' => 'narayaralian@yahoo.com',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-7.6.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
